generation:
  n: 5
  N: 50
  prob_noise_true: 0.1

mcmc:
  K: 2

prior:
  min_sub: 3.0
  rho_prior: 5.0
  mallow_ua: 1.0
  noise_beta_prior: 9.0


noise:
  noise_option: "queue_jump"


covariates:
  p: 2
  beta_true: [0.5, -0.3]

output:
  dir: "results"
  filename: "synthetic_data.json" 
  
  